GameExplorer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('games/', include('games.urls')),

]

accounts/urls.py
from accounts import views
from django.urls import path, include

urlpatterns = [
    path('register/', views.AccountRegisterView.as_view(), name='register'),
    path('login/', views.AccountLoginView.as_view(), name='login'),
    path('logout/', views.AccountLogoutView.as_view(), name='logout'),
    path('<int:id>/', include([
        path('', views.account_details, name='account-details'),
        path('edit/', views.AccountEditView.as_view(), name='account-edit'),
        path('delete/', views.account_delete, name='account-delete'),
        path('reviews/', views.AccountReviews.as_view(), name='account-reviews'),
    ])),
]

games/urls.py
from django.urls import path
from games import views

urlpatterns = [
    path('', views.GamesListView.as_view(), name='games-list'),
    path('all-games/', views.AllGamesView.as_view(), name='all-games'),
    path('add/', views.AddGame.as_view(), name='add-game'),
    path('<slug:slug>/', views.GameDetailView.as_view(), name='games-detail'),
    path('<slug:slug>/edit/', views.EditGame.as_view(), name='edit-game'),
    path('<slug:slug>/delete', views.delete_game, name='delete-game'),
    path('<slug:slug>/review/', views.GameReview.as_view(), name='games-review'),
    path('<slug:slug>/review/<int:id>/edit', views.EditGameReview.as_view(), name='edit-review'),
    path('<slug:slug>/review/<int:id>/delete', views.DeleteGameReview.as_view(), name='delete-review'),
    path('<slug:slug>/all-reviews/', views.GameListAllReviews.as_view(), name='game-all-reviews'),

    # API Views
    path('api/<slug:slug>/', views.ManageGameAPIView.as_view(), name='manage-games-api-view'),
    path('api/<slug:slug>/review/', views.ListAllGameReviewsAPIView.as_view(), name='list-all-game-reviews'),
    path('api/<slug:slug>/review/<int:id>/', views.ManageReviewAPIView.as_view(), name='modify-review'),
]

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models

from accounts.managers import AccountManager
from accounts.validators import NameValidator, UsernameValidator


# Create your models here.


class Account(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30, unique=True, validators=[UsernameValidator(3)])

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = AccountManager()


class Profile(models.Model):
    user = models.OneToOneField(
        'accounts.Account',
        on_delete=models.CASCADE,
        primary_key=True,
    )

    first_name = models.CharField(max_length=30, null=True, blank=True, validators=[NameValidator()])
    last_name = models.CharField(max_length=30, null=True, blank=True, validators=[NameValidator()])
    date_of_birth = models.DateField(null=True, blank=True)
    profile_picture = models.URLField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.user.username

games/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.text import slugify
from rest_framework.exceptions import ValidationError
from common.models import Platform, Genre
from common.validators import GamePlatformGenreNameValidator

# Create your models here.


class Game(models.Model):
    name = models.CharField(max_length=50, validators=[GamePlatformGenreNameValidator()], unique=True)
    release_date = models.DateField()
    genre = models.ManyToManyField(Genre)
    platform = models.ManyToManyField(Platform)
    developer = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    game_cover = models.URLField()
    trailer_url = models.URLField(null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True)

    def clean(self):
        if Game.objects.filter(slug=self.slug).exclude(id=self.id).exists():
            raise ValidationError({'slug': 'This slug is already taken. Please choose a different one.'})

        if not self.slug:
            self.slug = slugify(self.name)

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)


class Review(models.Model):
    game = models.ForeignKey('games.Game', on_delete=models.CASCADE)
    user = models.ForeignKey('accounts.Account', on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    review = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError

from accounts.models import Profile

UserModel = get_user_model()


class AccountRegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = UserModel
        fields = ('username', 'email', )

    def __init__(self, *args, **kwargs):
        super(AccountRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Create a username'})
        self.fields['email'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Enter your email address'})
        self.fields['password1'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Enter your password'})
        self.fields['password2'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Confirm your password'})


class AccountLoginForm(AuthenticationForm):
    username = forms.EmailField(widget=forms.EmailInput(attrs={'autofocus': True}))
    password = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'})
    )

    def __init__(self, *args, **kwargs):
        super(AccountLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Enter your email address'})
        self.fields['password'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Enter your password'})


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'date_of_birth', 'profile_picture', 'description']

    def __init__(self, *args, **kwargs):
        super(AccountEditForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Enter your first name'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Enter your last name'})
        self.fields['profile_picture'].widget.attrs.update({'class': 'form-input', 'placeholder': 'Attach a URL photo...'})
        self.fields['date_of_birth'].widget = forms.DateInput(attrs={'class': 'form-input date-input', 'placeholder': 'Enter your date of birth', 'type': 'date'})
        self.fields['description'].widget = forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Tell us about yourself...'})

accounts/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, UpdateView, ListView
from django.urls import reverse_lazy

from accounts.forms import AccountRegisterForm, AccountLoginForm, AccountEditForm
from accounts.models import Account, Profile
from games.models import Review


# Create your views here.
User = get_user_model()


class AccountRegisterView(CreateView):
    model = Account
    form_class = AccountRegisterForm
    success_url = reverse_lazy('index')
    template_name = 'accounts/register-page.html'

    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        return response

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('index')

        return super().dispatch(request,*args, **kwargs)


class AccountLoginView(LoginView):
    form_class = AccountLoginForm
    template_name = 'accounts/login-page.html'
    success_url = reverse_lazy('index')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('index')

        return super().dispatch(request, *args, **kwargs)


class AccountLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('login')

        return super().dispatch(request, *args, **kwargs)



@login_required
def account_details(request, id):
    account = get_object_or_404(User, id=id)

    context = {
        'account': account,
    }

    return render(request, 'accounts/account-details-page.html', context)


class AccountEditView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = AccountEditForm
    template_name = 'accounts/account-edit-page.html'
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('account-details')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['account'] = self.request.user
        return context

    def get_object(self, queryset=None):
        profile = Profile.objects.get(pk=self.kwargs['id'])
        if profile.user != self.request.user:
            raise PermissionDenied("You do not have permission to edit this profile.")

        return profile

    def get_success_url(self):
        return reverse_lazy('account-details', kwargs={'id': self.object.user.id})


def account_delete(request, id):
    account = get_object_or_404(User, id=id)
    context = {'account': account}

    if account != request.user:
        raise PermissionDenied("You do not have permission to delete this account.")

    if request.method == 'POST':
        account.delete()
        return redirect('index')

    return render(request, 'accounts/close-account-page.html', context)


class AccountReviews(ListView):
    template_name = 'accounts/account-reviews.html'
    paginate_by = 5

    def get_queryset(self):
        review_object = Review.objects.all().filter(user_id=self.kwargs['id'])
        return review_object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['account'] = User.objects.get(id=self.kwargs['id'])
        return context

templates/accounts/account-details-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="user-details-block">
    <section class="user-card">
        <div class="user-visualization">
            <div class="user-photo">
                {% if account.profile.profile_picture %}
                    <img src="{{ account.profile.profile_picture }}" alt="">
                {% else %}
                    <img src="{% static 'user/no-photo-user.png' %}" alt="">
                {% endif %}
            </div>
            <div class="user-name-card">
                {% if account.profile.first_name and account.profile.last_name %}
                    <h2>{{ account.profile.first_name }} {{ account.profile.last_name }}</h2>
                {% elif account.profile.first_name %}
                    <h2>{{ account.profile.first_name }}</h2>
                {% elif account.profile.last_name %}
                    <h2>{{ account.profile.last_name }}</h2>
                {% endif %}
            </div>
        </div>



        <div class="user-details">
            <h1>INFORMATION</h1>

            <h2>USERNAME: {{ account.username }}</h2>
            <h2>DATE OF BIRTH: {% if account.profile.date_of_birth %}
                {{ account.profile.date_of_birth }} {% else %} No information provided</h2>
            {% endif %}
            <h2>GAMES PLAYED: {% if account.review_set %} {{ account.review_set.count }} {% else %} 0 {% endif %}</h2> {#continue once the backend logic is completed#}
            {% if account.review_set.count > 0 %}
                <h2><a href="{% url 'account-reviews' account.id %}">ALL REVIEWS</a></h2>
            {% endif %}
            <p>{% if account.profile.description %} {{ account.profile.description }} {% endif %}</p>
        </div>
    </section>
                {% if account.id == request.user.id %}
                <div class="user-buttons">
                    <a href="{% url 'account-edit' account.id %}"><button>EDIT DETAILS</button></a>
                    <a href="{% url 'account-delete' account.id %}"><button>CLOSE ACCOUNT</button></a>
               {% endif %}

        </div>
</div>


{% endblock %}

templates/accounts/account-edit-page.html
{% extends 'base.html' %}

{% block content %}

<section class="form-container">
    <div class="form-div">
        <h2>Edit Profile Details</h2>
        <form class="account-form-div" method='POST' action="">
            {% csrf_token %}
            {{ form.first_name }}
            {% if form.first_name.errors %}
                <div class="form-error">
                    {{ form.first_name.errors }}
                </div>
            {% endif %}
            {{ form.last_name }}
                    {% if form.last_name.errors %}
                <div class="form-error">
                    {{ form.last_name.errors }}
                </div>
            {% endif %}
            {{ form.profile_picture }}
            {{ form.date_of_birth }}
            {{ form.description }}
            <button>Save</button>
        </form>
    </div>
</section>
{% endblock %}

templates/accounts/account-reviews.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>All reviews by {{ account.username }}</h2>
<div class="reviews-container">
    {% if object_list %}
    {% for review in object_list %}
        <div class="review-card">
            <div class="review-card-reviewer-details">
                <div class="game-photo-review">
                        <a href="{% url 'games-detail' slug=review.game.slug %}"><img src="{{ review.game.game_cover }}" alt=""></a>
                </div>
            </div>
            <div class="review-card-review-details">
                <p>Player rating: {{ review.rating }} / 5</p>
                <p>{% if review.review %}{{ review.review }} {% else %} Comment not provided. {% endif %}</p>
                <h4>{{ review.created_at|date:"j F, Y" }}</h4>
                <div class="review-buttons">
                {% if account == request.user %}
                    <a href="{% url 'edit-review' slug=review.game.slug id=review.id %}"><button>Edit</button></a>
                {% endif %}
                {% if account == request.user or request.user.is_staff %}
                    <a href="{% url 'delete-review' slug=review.game.slug id=review.id %}"><button>Delete</button></a>
                {% endif %}
                </div>
            </div>
        </div>

    {% endfor %}
    {% else %}
    <h2>No reviews yet...</h2>
    {% endif %}


</div>
    <br>
    <br>
    <div class="pagination">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class='page-button'href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in paginator.page_range %}
            {% if page_obj.number == num %}
                <strong>{{ num }}</strong>
            {% else %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class='page-button'href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

templates/accounts/close-account-page.html
{% extends 'base.html' %}

{% block content %}\
<div class="account-close-page">
    <h1>Are you sure you want to close the account?</h1>
    <h2>This action is permanent.</h2>
    <div class="delete-buttons-container">
        <a href="{% url 'index' %}"><button>No</button></a>
        <form method="POST" action="">
            {% csrf_token %}
            <button>Yes</button>
        </form>

    </div>
</div>

{% endblock %}

templates/accounts/login-page.html
{% extends 'base.html' %}
{% block content %}

<section class="form-container">
    <div class="form-div">
        <h2>Log into your account</h2>
        <form class="account-form-div" method='POST' action="">
            {% csrf_token %}
            {{ form.username }}
            {{ form.password }}

            {% if form.non_field_errors %}
                <div class="form-error">
                    {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                 </div>
            {% endif %}

            <button type="submit">Log in</button>
        </form>
    </div>
</section>
{% endblock %}

templates/accounts/register-page.html
{% extends 'base.html' %}
{% block content %}

<section class="form-container">
    <div class="form-div">
        <h2>Create an account</h2>
        <form class="account-form-div" method='POST' action="">
            {% csrf_token %}
            {{ form.username }}
            {% if form.username.errors %}
                <div class="form-error">
                    {% for error in form.username.errors %}
                        <p>{{ error }}</p>
                </div>
                    {% endfor %}
            {% endif %}
            {{ form.email }}
            {% if form.email.errors %}
                <div class="form-error">
                    {% for error in form.email.errors %}
                        <p>{{ error }}</p>
                </div>
                    {% endfor %}
            {% endif %}
            {{ form.password1 }}
            {% if form.password1.errors %}
                <div class="form-error">
                    {% for error in form.password1.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
            {% endif %}
        {{ form.password2 }}
            {% if form.password2.errors %}
                <div class="form-error">
                    {% for error in form.password2.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            <button type="submit">Register</button>

        </form>
    </div>
</section>

{% endblock %}